'use client';

import { useState, useEffect, useRef, useCallback } from 'react';
import { useWebSocket } from '@/hooks/useWebSocket';
import { API_URL, WS_URL } from '@/lib/config';

interface Post {
  channel: string;
  postId: number;
  commentText: string | null;
  createdAt: string | null;
}

interface User {
  id: number;
  telegramId: number;
  username: string | null;
  firstName: string | null;
  lastName: string | null;
  photoUrl: string | null;
}

type AuthFlowState = 'idle' | 'loading' | 'waiting' | 'success';

// Mock posts for preview when not authenticated
const MOCK_POSTS: Post[] = [
  {
    channel: 'durov',
    postId: 123,
    commentText: 'This is a preview comment that demonstrates how AI-generated comments look in the feed.',
    createdAt: new Date().toISOString(),
  },
  {
    channel: 'telegram',
    postId: 456,
    commentText: 'Another example of an intelligent comment generated by our AI system for engagement.',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    channel: 'techcrunch',
    postId: 789,
    commentText: 'Great insights! The AI creates contextual responses based on the post content.',
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
];

// Telegram Post Widget
function TelegramPost({ channel, postId }: { channel: string; postId: number }) {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!containerRef.current) return;
    containerRef.current.innerHTML = '';

    const script = document.createElement('script');
    script.src = 'https://telegram.org/js/telegram-widget.js?22';
    script.async = true;
    script.setAttribute('data-telegram-post', `${channel}/${postId}`);
    script.setAttribute('data-width', '100%');

    containerRef.current.appendChild(script);
  }, [channel, postId]);

  return <div ref={containerRef} className="w-full p-2 [&_iframe]:rounded-lg" />;
}

// Regular post card (authenticated)
function PostCard({ post, formatTime }: { post: Post; formatTime: (s: string | null) => string }) {
  const [expanded, setExpanded] = useState(false);

  return (
    <div className="bg-neutral-900 border border-neutral-800 rounded-lg hover:border-neutral-700 transition-all duration-300 overflow-hidden shrink-0 hover:shadow-md hover:shadow-accent-500/5">
      <div className={`p-4 ${expanded ? 'border-b border-neutral-800' : ''}`}>
        <div className="flex justify-between items-start gap-3 mb-3">
          <a
            href={`https://t.me/${post.channel}`}
            target="_blank"
            rel="noopener noreferrer"
            className="text-xs uppercase tracking-wide text-accent-500 hover:text-accent-400 transition-all duration-200 truncate hover:underline"
          >
            @{post.channel}
          </a>
          <div className="flex items-center gap-2 shrink-0">
            <span className="text-xs tabular-nums text-tertiary whitespace-nowrap">
              {formatTime(post.createdAt)}
            </span>
            <button
              onClick={() => setExpanded(!expanded)}
              className="text-tertiary hover:text-secondary transition-all duration-200 text-xs px-2 py-1 rounded-md hover:bg-neutral-850"
            >
              {expanded ? 'Скрыть' : 'Показать'}
            </button>
          </div>
        </div>
        <p className="text-base leading-relaxed text-primary wrap-break-word">
          {post.commentText || '—'}
        </p>
      </div>
      {expanded && (
        <div className="border-t border-neutral-800">
          <TelegramPost channel={post.channel} postId={post.postId} />
        </div>
      )}
    </div>
  );
}

// Blurred post card for preview (not authenticated)
function BlurredPostCard({ post, formatTime }: { post: Post; formatTime: (s: string | null) => string }) {
  return (
    <div className="bg-neutral-900 border border-neutral-800 rounded-lg overflow-hidden shrink-0">
      <div className="p-4">
        <div className="flex justify-between items-start gap-3 mb-3">
          <span className="text-xs uppercase tracking-wide text-accent-500/60">@{post.channel}</span>
          <span className="text-xs tabular-nums text-tertiary/60 whitespace-nowrap">
            {formatTime(post.createdAt)}
          </span>
        </div>
        <p className="text-base leading-relaxed text-primary/80 blur-[3px] select-none">
          {post.commentText || '—'}
        </p>
      </div>
    </div>
  );
}

// Telegram icon
function TelegramIcon({ className = '' }: { className?: string }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="currentColor">
      <path d="M11.944 0A12 12 0 0 0 0 12a12 12 0 0 0 12 12 12 12 0 0 0 12-12A12 12 0 0 0 12 0a12 12 0 0 0-.056 0zm4.962 7.224c.1-.002.321.023.465.14a.506.506 0 0 1 .171.325c.016.093.036.306.02.472-.18 1.898-.962 6.502-1.36 8.627-.168.9-.499 1.201-.82 1.23-.696.065-1.225-.46-1.9-.902-1.056-.693-1.653-1.124-2.678-1.8-1.185-.78-.417-1.21.258-1.91.177-.184 3.247-2.977 3.307-3.23.007-.032.014-.15-.056-.212s-.174-.041-.249-.024c-.106.024-1.793 1.14-5.061 3.345-.48.33-.913.49-1.302.48-.428-.008-1.252-.241-1.865-.44-.752-.245-1.349-.374-1.297-.789.027-.216.325-.437.893-.663 3.498-1.524 5.83-2.529 6.998-3.014 3.332-1.386 4.025-1.627 4.476-1.635z" />
    </svg>
  );
}

export function RecentPosts() {
  // Auth state
  const [isAuthenticated, setIsAuthenticated] = useState<boolean | null>(null);
  const [user, setUser] = useState<User | null>(null);
  const [authFlowState, setAuthFlowState] = useState<AuthFlowState>('idle');
  const [deepLink, setDeepLink] = useState<string | null>(null);
  const [qrDataUrl, setQrDataUrl] = useState<string | null>(null);
  const wsRef = useRef<WebSocket | null>(null);

  // Posts state
  const [posts, setPosts] = useState<Post[]>([]);
  const [loading, setLoading] = useState(true);
  const [loadingMore, setLoadingMore] = useState(false);
  const [hasMore, setHasMore] = useState(true);
  const observerRef = useRef<IntersectionObserver | null>(null);
  const loadMoreRef = useRef<HTMLDivElement>(null);
  const limit = 10;

  // Check auth on mount
  useEffect(() => {
    const sessionId = localStorage.getItem('sessionId');
    const savedUser = localStorage.getItem('user');
    if (sessionId && savedUser) {
      setIsAuthenticated(true);
      setUser(JSON.parse(savedUser));
    } else {
      setIsAuthenticated(false);
      setLoading(false);
    }
  }, []);

  // Cleanup WebSocket on unmount
  useEffect(() => {
    return () => {
      if (wsRef.current) {
        wsRef.current.close();
      }
    };
  }, []);

  // Generate QR code when deepLink changes
  useEffect(() => {
    if (!deepLink) return;

    async function generateQR() {
      try {
        const QRCodeLib = await import('qrcode');
        const isDark = !document.documentElement.classList.contains('light');
        const url = await QRCodeLib.toDataURL(deepLink!, {
          width: 180,
          margin: 2,
          color: {
            dark: isDark ? '#fafafa' : '#1a1a1f',
            light: '#00000000',
          },
          errorCorrectionLevel: 'M',
        });
        setQrDataUrl(url);
      } catch (err) {
        console.error('QR generation failed:', err);
      }
    }
    generateQR();
  }, [deepLink]);

  // Start login flow
  const startLogin = useCallback(async () => {
    try {
      setAuthFlowState('loading');

      const res = await fetch(`${API_URL}/auth/login`, { method: 'POST' });
      const data = await res.json();

      if (data.token && data.deepLink) {
        setDeepLink(data.deepLink);
        setAuthFlowState('waiting');

        // Connect WebSocket
        if (wsRef.current) {
          wsRef.current.close();
        }

        const ws = new WebSocket(WS_URL);
        wsRef.current = ws;

        ws.onopen = () => {
          ws.send(JSON.stringify({ type: 'auth:subscribe', token: data.token }));
        };

        ws.onmessage = (event) => {
          try {
            const message = JSON.parse(event.data);

            if (message.type === 'auth:confirmed') {
              const { sessionId, user: confirmedUser } = message.data as { sessionId: string; user: User };

              // Save session
              document.cookie = `session=${sessionId}; path=/; max-age=${30 * 24 * 60 * 60}; SameSite=Lax`;
              localStorage.setItem('sessionId', sessionId);
              localStorage.setItem('user', JSON.stringify(confirmedUser));

              setAuthFlowState('success');
              ws.close();

              // Update state after animation
              setTimeout(() => {
                setIsAuthenticated(true);
                setUser(confirmedUser);
              }, 800);
            }
          } catch (error) {
            console.error('WebSocket message parse error:', error);
          }
        };
      }
    } catch (error) {
      console.error('Login failed:', error);
      setAuthFlowState('idle');
    }
  }, []);

  // Cancel login flow
  const cancelLogin = useCallback(() => {
    if (wsRef.current) {
      wsRef.current.close();
    }
    setAuthFlowState('idle');
    setDeepLink(null);
    setQrDataUrl(null);
  }, []);

  // Handle logout
  const handleLogout = useCallback(() => {
    localStorage.removeItem('sessionId');
    localStorage.removeItem('user');
    document.cookie = 'session=; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT';
    setIsAuthenticated(false);
    setUser(null);
    setPosts([]);
    setAuthFlowState('idle');
  }, []);

  // WebSocket for real-time updates
  const handleWsMessage = useCallback((msg: { type: string; data: unknown }) => {
    if (msg.type === 'new_comment') {
      const data = msg.data as { channel: string; postId: number; commentText: string; createdAt: string };
      setPosts((prev) => [
        { channel: data.channel, postId: data.postId, commentText: data.commentText, createdAt: data.createdAt },
        ...prev,
      ]);
    }
  }, []);

  useWebSocket(handleWsMessage);

  // Fetch posts
  const fetchPosts = useCallback(async (offset: number, append = false) => {
    try {
      if (append) setLoadingMore(true);
      const res = await fetch(`${API_URL}/api/recent-posts?limit=${limit}&offset=${offset}`);
      if (res.ok) {
        const data = await res.json();
        if (data.posts.length < limit) setHasMore(false);
        setPosts((prev) => (append ? [...prev, ...data.posts] : data.posts));
      }
    } catch (error) {
      console.error('Failed to fetch posts:', error);
    } finally {
      setLoading(false);
      setLoadingMore(false);
    }
  }, []);

  useEffect(() => {
    if (isAuthenticated) {
      fetchPosts(0);
    }
  }, [fetchPosts, isAuthenticated]);

  // Intersection Observer for lazy loading
  useEffect(() => {
    if (loading || !isAuthenticated) return;

    observerRef.current = new IntersectionObserver(
      (entries) => {
        if (entries[0].isIntersecting && hasMore && !loadingMore) {
          fetchPosts(posts.length, true);
        }
      },
      { threshold: 0.1 }
    );

    if (loadMoreRef.current) {
      observerRef.current.observe(loadMoreRef.current);
    }

    return () => observerRef.current?.disconnect();
  }, [loading, hasMore, loadingMore, posts.length, fetchPosts, isAuthenticated]);

  const formatTime = (isoString: string | null) => {
    if (!isoString) return '';
    const date = new Date(isoString);
    return date.toLocaleString('ru-RU', {
      day: 'numeric',
      month: 'short',
      hour: '2-digit',
      minute: '2-digit',
      timeZone: 'Europe/Moscow',
    });
  };

  // Header component
  const Header = ({ showLogout = false }: { showLogout?: boolean }) => (
    <div className="mb-4 pb-4 border-b border-neutral-800 shrink-0 flex items-start justify-between">
      <div>
        <p className="text-xs uppercase tracking-wide text-tertiary mb-2">Последние комментарии</p>
        <h2 className="text-lg font-semibold text-primary">Прокомментированные посты</h2>
      </div>
      {showLogout && user && (
        <div className="flex items-center gap-2">
          <span className="text-xs text-tertiary">{user.firstName || user.username}</span>
          <button onClick={handleLogout} className="text-xs text-text-disabled hover:text-text-secondary transition-colors">
            Выйти
          </button>
        </div>
      )}
    </div>
  );

  // Not authenticated — show auth flow inline
  // Blur posts + gradient ALWAYS visible, glass box changes content
  if (isAuthenticated === false) {
    return (
      <div className="bg-neutral-900 rounded-xl p-4 md:p-6 border border-neutral-800 h-full flex flex-col relative overflow-hidden">
        <Header />

        {/* Blur posts — ALWAYS visible */}
        <div className="flex flex-col gap-3 flex-1 min-h-0">
          {MOCK_POSTS.map((post, index) => (
            <BlurredPostCard key={index} post={post} formatTime={formatTime} />
          ))}
        </div>

        {/* Gradient overlay — ALWAYS visible */}
        <div className="absolute inset-0 pointer-events-none rounded-xl">
          <div className="absolute bottom-0 left-0 right-0 h-4/5 bg-linear-to-t from-neutral-900 via-neutral-900/95 to-transparent" />
        </div>

        {/* Glass box — fixed size, content changes based on state */}
        <div className="absolute bottom-6 left-4 right-4 pointer-events-auto">
          <div className="bg-neutral-900/70 backdrop-blur-xl border border-neutral-700/50 rounded-2xl p-6 shadow-2xl shadow-black/30 text-center max-w-xs mx-auto h-80 flex flex-col justify-center">

            {/* Idle state — CTA */}
            {authFlowState === 'idle' && (
              <div className="animate-modal-content">
                <div className="w-14 h-14 mx-auto mb-4 rounded-xl bg-accent-500/10 flex items-center justify-center">
                  <svg className="w-7 h-7 text-accent-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
                    <rect x="3" y="11" width="18" height="11" rx="2" ry="2" />
                    <path d="M7 11V7a5 5 0 0 1 10 0v4" />
                  </svg>
                </div>
                <h3 className="text-lg font-semibold text-primary mb-2">Доступ к комментариям</h3>
                <p className="text-sm text-tertiary mb-5">Войдите чтобы видеть все AI-комментарии</p>
                <button
                  onClick={startLogin}
                  className="w-full inline-flex items-center justify-center gap-2 bg-[#2AABEE] hover:bg-[#229ED9] text-white font-medium rounded-xl px-5 py-3 transition-colors shadow-lg shadow-[#2AABEE]/20"
                >
                  <TelegramIcon className="w-5 h-5" />
                  Войти через Telegram
                </button>
              </div>
            )}

            {/* Loading state — spinner */}
            {authFlowState === 'loading' && (
              <div className="animate-modal-fade">
                <div className="w-14 h-14 mx-auto mb-4 rounded-xl bg-accent-500/10 flex items-center justify-center">
                  <TelegramIcon className="w-7 h-7 text-accent-400" />
                </div>
                <div className="flex items-center justify-center gap-2 text-tertiary">
                  <div className="w-4 h-4 border-2 border-accent-500/20 border-t-accent-500 rounded-full animate-spin" />
                  <span className="text-sm">Подготовка...</span>
                </div>
              </div>
            )}

            {/* Waiting state — QR code */}
            {authFlowState === 'waiting' && deepLink && (
              <div className="space-y-4 animate-modal-fade">
                {/* QR Code */}
                {qrDataUrl ? (
                  <div className="relative inline-block mx-auto animate-qr-scale">
                    <div className="bg-neutral-850/80 p-3 rounded-xl border border-neutral-700/50">
                      <img src={qrDataUrl} alt="QR Code" width={140} height={140} className="block" />
                    </div>
                    <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-8 h-8 bg-neutral-900 rounded-lg flex items-center justify-center border border-neutral-700/50">
                      <TelegramIcon className="w-5 h-5 text-[#2AABEE]" />
                    </div>
                  </div>
                ) : (
                  <div className="w-35 h-35 bg-neutral-800/50 rounded-xl mx-auto flex items-center justify-center">
                    <div className="w-5 h-5 border-2 border-accent-500/20 border-t-accent-500 rounded-full animate-spin" />
                  </div>
                )}

                <div>
                  <p className="text-sm text-tertiary">
                    Отсканируйте или{' '}
                    <a
                      href={deepLink}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-accent-400 hover:text-accent-300 underline underline-offset-2"
                    >
                      откройте в Telegram
                    </a>
                  </p>
                </div>

                <div className="flex items-center justify-center gap-2 text-tertiary">
                  <div className="w-3 h-3 border-2 border-accent-500/20 border-t-accent-500 rounded-full animate-spin" />
                  <span className="text-xs">Ожидание...</span>
                </div>

                <button
                  onClick={cancelLogin}
                  className="text-xs text-tertiary hover:text-secondary transition-colors"
                >
                  Отмена
                </button>
              </div>
            )}

            {/* Success state — checkmark */}
            {authFlowState === 'success' && (
              <div className="animate-qr-scale">
                <div className="w-14 h-14 mx-auto mb-4 rounded-full bg-success/20 flex items-center justify-center">
                  <svg className="w-7 h-7 text-success" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3">
                    <path d="M5 13l4 4L19 7" strokeLinecap="round" strokeLinejoin="round" />
                  </svg>
                </div>
                <p className="text-success font-medium">Успешно!</p>
              </div>
            )}
          </div>
        </div>
      </div>
    );
  }

  // Loading posts
  if (loading) {
    return (
      <div className="bg-neutral-900 rounded-xl p-4 md:p-6 border border-neutral-800 h-full flex flex-col">
        <Header />
        <div className="flex flex-col gap-3 overflow-y-auto flex-1 min-h-0">
          {[1, 2, 3].map((i) => (
            <div key={i} className="bg-neutral-850 rounded-lg h-20 border border-neutral-800 shrink-0">
              <div className="h-full w-full relative overflow-hidden">
                <div className="absolute inset-0 bg-gradient-to-r from-transparent via-neutral-800/50 to-transparent animate-shimmer" />
              </div>
            </div>
          ))}
        </div>
      </div>
    );
  }

  // Empty state
  if (posts.length === 0) {
    return (
      <div className="bg-neutral-900 rounded-xl p-4 md:p-6 border border-neutral-800 h-full flex flex-col">
        <Header showLogout />
        <div className="flex-1 flex items-center justify-center">
          <p className="text-tertiary">Нет прокомментированных постов</p>
        </div>
      </div>
    );
  }

  // Authenticated — show posts
  return (
    <div className="bg-neutral-900 rounded-xl p-4 md:p-6 border border-neutral-800 h-full flex flex-col">
      <Header showLogout />
      <div className="flex flex-col gap-3 overflow-y-auto flex-1 min-h-0 pr-2">
        {posts.map((post, index) => (
          <PostCard key={`${post.channel}-${post.postId}-${index}`} post={post} formatTime={formatTime} />
        ))}
        <div ref={loadMoreRef} className="h-10 shrink-0">
          {loadingMore && <div className="text-center text-tertiary py-2 text-sm">Загрузка...</div>}
          {!hasMore && posts.length > 0 && (
            <div className="text-center text-disabled py-2 text-xs">Все посты загружены</div>
          )}
        </div>
      </div>
    </div>
  );
}
